package main

import c "github.com/Micah-Shallom/modules/challenges"

func main() {
	// c.Twosums()
	// c.MaxProfit()
	// c.Duplicate()
	// c.RemoveDuplicates()
	// c.ManipulatingJSON()
	// c.VaSolution()
	// c.ArrayConcate()
	// c.ReplaceGreatest()
	// c.IsSequence()
	// c.LengthLastWord()
	// c.LCP()
	// c.UniqueEmails()
	// c.IsIsomorphic()
	// c.MajorityElements()
	// c.NextGreaterElement()
	// c.FindPivotIndex()
	// c.RangeSumQuery()
	// c.FindDisappearedNums()
	// c.WordPattern()
	// c.MyHashSet()
	// c.DesignHashSet()
	// c.DesignHashMap()
	// c.ValidPalindrome()
	// c.ValidParenthesis()
	// c.MinimumDifference()
	// c.BaseBallGame()
	// c.DailyTemperatures()
	// c.DivideArray()
	// c.FirstUnique()
	// c.FrequencySort()
	// c.NumSubArray()
	// c.FirstPalindrome()
	// c.MergeAlternately()
	// c.LengthOfLongestSubString()
	// c.ReverseLL()
	// c.MergeTwoLL()
	// c.GuessNumber()
	// c.MaximumOddBinaryNumber()
	// c.SortedSquares()
	// c.RemoveNthFromEnd()
	// c.BagOfTokensScore()
	// c.MinimumLength()
	// c.HasCycle()
	// c.MaxFrequencyElements()
	// c.InOrderTraversal()
	// c.GetCommon()
	// c.Intersection()
	// c.CustomSortString()
	// c.RemoveZeroSumSublists()
	// c.PivotInteger()
	// c.NumSubarraysWithSum()
	// c.FindMaxLength()
	// c.Insert()
	// c.FindMinArrowShots()
	// c.LeastInterval()
	c.MergeInBetween()
}
